# Generated by Django 4.1.2 on 2022-11-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('color', 'Color')], max_length=100),
        ),
    ]
