# Generated by Django 4.1.2 on 2022-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(blank=True, null=True, verbose_name='offer price'),
        ),
    ]
