# Generated by Django 4.1.2 on 2022-11-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproduct_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=False),
        ),
    ]
